kind: Template
apiVersion: v1
metadata:
  name: build-integration
objects:
  - apiVersion: camel.apache.org/v1
    kind: Integration
    metadata:
      name: camel-k-perf
    spec:
      flows:
      - from:
          parameters:
              period: "50000"
          steps:
          - set-body:
              constant: Hello Yaml !!!
          - transform:
              simple: ${body.toUpperCase()}
          - to: log:info
          uri: timer:tick
      traits:
        builder:
          configuration:
            properties:
            - build-property = 1
