kind: Template
apiVersion: v1
metadata:
  name: platform-integration
objects:
  - apiVersion: camel.apache.org/v1
    kind: IntegrationPlatform
    metadata:
      name: camel-k
    spec:
      build:
        buildStrategy: pod
      traits:
        gc:
          configuration:
            enabled: false
  - apiVersion: camel.apache.org/v1
    kind: Integration
    metadata:
      name: camel-k-perf
    spec:
      flows:
      - from:
          parameters:
            period: "50000"
          steps:
          - set-body:
              constant: Hello Yaml !!!
          - transform:
              simple: ${body.toUpperCase()}
          - to: log:info
          uri: timer:tick
